# Generated by Django 5.0.14 on 2026-10-06 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre Comercial')),
                ('laboratorio', models.CharField(max_length=100)),
                ('precio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='El precio debe ser mayor a 0')])),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='El stock no puede ser negativo')])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('requiere_receta', models.BooleanField(default=False)),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
    ]
